import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";
import { validateTokenAndRedirectLogin } from "@/utils/tokenValidity";
import { Box, Button } from "@mui/material";
import { Header } from "@/components/Header";
import { useState } from "react";
import { useSkills } from "@/hooks/useSkills";
import SkillModal from "@/components/SkillModal";
import SkillListing from "@/components/SkillListing";
import { CreateSkillInput } from "@/apiCalls/skills";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { skills, isLoading, error, updateSkill, deleteSkill } = useSkills();
  const [modalOpen, setModalOpen] = useState(false);
  const [editingSkill, setEditingSkill] = useState<any>(null);

  const handleCreate = () => {
    setEditingSkill(null);
    setModalOpen(true);
  };

  const handleEdit = (skill: CreateSkillInput) => {
    setEditingSkill(skill);
    setModalOpen(true);
  };

  const handleSubmit = async (data: CreateSkillInput) => {
    await updateSkill({ ...data, id: editingSkill?.id || null });
    setModalOpen(false);
  };

  const handleDelete = async (id: string) => {
    try {
      await deleteSkill(id);
      setModalOpen(false);
    } catch (error) {
      console.error("Error deleting skill:", error);
    }
  };

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error loading skills</div>;

  return (
    <>
      <Header />
      <Head>
        <title>Skill Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Box display="flex" p={2}>
          <Button variant="contained" onClick={handleCreate}>
            Create Skill
          </Button>
        </Box>
        <SkillListing skills={skills} onEdit={handleEdit} />
        <SkillModal
          key={editingSkill ? editingSkill.id : "new-skill-modal"}
          open={modalOpen}
          onClose={() => setModalOpen(false)}
          onSubmit={handleSubmit}
          onDelete={handleDelete}
          initialData={editingSkill}
        />
        <main className={styles.main}></main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tokenCheck = await validateTokenAndRedirectLogin(context);
  if (tokenCheck.redirect) return tokenCheck;

  return {
    props: {
      user: tokenCheck.user,
    },
  };
};
